#!/usr/bin/env python
# -*- coding: utf-8 -*-
import getpass
import sys
from optparse import OptionParser

from pyswedbank.wrapper import Swedbank


def main():
    """ Main """
    usage = "usage: %prog [options]"
    parser = OptionParser(usage=usage)
    parser.add_option("-u", "--username",
                      metavar="username", help="Username")
    parser.add_option("-p", "--password",
                      metavar="passwd", help="Password")
    parser.add_option("-b", "--bank",
                      metavar="bank", help="Choose which bank you want to use.\nDefault first bank", default="swedbank")
    parser.add_option("-B", "--list-banks",
                      action="store_true", dest="listbanks", default=False, help="List banks to choose from")
    parser.add_option("-t", "--transactions",
                      action="store_true", dest="transactions", help="Show all available transactions for account.")
    (options, args) = parser.parse_args()

    swed = Swedbank()
    if options.listbanks:
        swed.listbanks()
        sys.exit(2)

    if not options.username:
        print("Missing username!")
        sys.exit(1)
    else:
        username = options.username

    if options.password:
        password = options.password
    else:
        password = getpass.getpass()

    bank = options.bank

    if not password:
        print("Missing password!")
        sys.exit(1)

    if swed.login(username, password, bank):
        swed.accounts()
        if options.transactions:
            swed.history()

if __name__ == "__main__":
    sys.exit(main())
